name: template_skeleton
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.0.0
  dart_jts: ^0.2.1+1
  latlong2: ^0.8.1
  flutter_map_marker_cluster: ^1.0.0
  point_in_polygon: ^1.0.0
  geojson_vi: ^2.0.7
  http: ^0.13.5
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  collection: ^1.16.0
  tuple: ^2.0.0
  geobase: ^0.3.2
  proj4dart: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
